version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: countdb
      MYSQL_USER: countuser
      MYSQL_PASSWORD: countpw
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: ./api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: countdb
      DB_USER: countuser
      DB_PASSWORD: countpw
    ports:
      - "8080:8080"
  front:
    build: ./front
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  db_data: 