name: CD

on:
  push:
    branches: 
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 커스텀 네트워크 생성 (이미 있으면 에러 무시)
            docker network create mynet || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/api-server:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/front-server:latest
            docker pull mysql:8.0
            docker stop api-server || true
            docker stop front-server || true
            docker stop db || true
            docker rm api-server || true
            docker rm front-server || true
            docker rm db || true
            docker run -d --name db --network mynet \
              -e MYSQL_ROOT_PASSWORD=rootpw \
              -e MYSQL_DATABASE=countdb \
              -e MYSQL_USER=countuser \
              -e MYSQL_PASSWORD=countpw \
              -p 3306:3306 \
              mysql:8.0
            docker run -d --name api-server --network mynet -p 8081:8080 ${{ secrets.DOCKERHUB_USERNAME }}/api-server:latest
            docker run -d --name front-server --network mynet -p 8080:3000 ${{ secrets.DOCKERHUB_USERNAME }}/front-server:latest 