name: CI

on:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build API with Maven
        run: mvn -B clean package -f api/pom.xml

      - name: Build Front with Maven
        run: mvn -B clean package -f front/pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-server:latest ./api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-server:latest

      - name: Build and push Front Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/front-server:latest ./front
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/front-server:latest 